[General]
score_plugin_LocalTree=true

[Audio]
AutoConnect=false
AutoStereo=true
BufferSize=1024
CardIn=pipewire
CardOut=pipewire
DefaultIn=2
DefaultOut=128
Driver=@Variant(\0\0\0\x7f\0\0\0!Audio::AudioFactory::ConcreteKey\0\x13\xda\xbc\xc3\x9c\xda\x42/\xa8\xc7_\xef\\\"\x6w)
InputNames=in_0, in_1
JackTransport=@Variant(\0\0\0\x7f\0\0\0#Audio::Settings::ExternalTransport\0\0)
OutputNames=out_0, out_1, out_2, out_3, out_4, out_5, out_6, out_7, out_8, out_9, out_10, out_11, out_12, out_13, out_14, out_15, out_16, out_17, out_18, out_19, out_20, out_21, out_22, out_23, out_24, out_25, out_26, out_27, out_28, out_29, out_30, out_31, out_32, out_33, out_34, out_35, out_36, out_37, out_38, out_39, out_40, out_41, out_42, out_43, out_44, out_45, out_46, out_47, out_48, out_49, out_50, out_51, out_52, out_53, out_54, out_55, out_56, out_57, out_58, out_59, out_60, out_61, out_62, out_63, out_64, out_65, out_66, out_67, out_68, out_69, out_70, out_71, out_72, out_73, out_74, out_75, out_76, out_77, out_78, out_79, out_80, out_81, out_82, out_83, out_84, out_85, out_86, out_87, out_88, out_89, out_90, out_91, out_92, out_93, out_94, out_95, out_96, out_97, out_98, out_99, out_100, out_101, out_102, out_103, out_104, out_105, out_106, out_107, out_108, out_109, out_110, out_111, out_112, out_113, out_114, out_115, out_116, out_117, out_118, out_119, out_120, out_121, out_122, out_123, out_124, out_125, out_126, out_127
SamplingRate=44100

[Effect]
ClapPaths=/home/edu/.clap, /usr/lib/clap, /usr/local/lib/clap, /usr/lib64/clap, /usr/local/lib64/clap
Lv2Paths=/home/edu/.lv2, /usr/lib/lv2, /usr/local/lib/lv2, /usr/lib64/lv2, /usr/local/lib64/lv2
Vst3Paths=/home/edu/.vst3, /usr/lib/vst3, /usr/lib64/vst3
VstPaths=/home/edu/.vst, /usr/lib/vst, /usr/lib/lxvst, /usr/lib64/vst, /usr/lib64/lxvst, /home/edu/.vst3

[Library]
RootPath=/home/edu/Documents/ossia/score

[Network]
ClientName=score
ClientPort=7777
MasterPort=8888
PlayerPort=0

[Protocols]
MidiAPI=ALSA (sequencer)

[RemoteControl]
Enabled=false
ServerAddress=0.0.0.0
ServerEnabled=false
ServerPort=@Variant(\0\0\0\x85'\x7f)
WebUiPath=/home/edu/Documents/ossia/score/packages/wasm-remote/

[Scenario]
AutoSequence=false
ExecutionRefreshRate=60
ExecutionUpdate=true
MagneticMeasures=true
MeasureBars=false
SnapshotOnCreate=false
TimeBar=true
UpdateRate=60

[Skin]
DefaultEditor=
ProcessUIPlacement=Central
ScriptEditorPlacement=Side panel
ScriptEditorPreview=Background
Skin=Default
Zoom=1
defaultDuration=@Variant(\0\0\0\x7f\0\0\0\bTimeVal\0\0\0\0\x2v\xdb\x6\0)
slotHeight=200

[score_plugin_curve]
Mode=@Variant(\0\0\0\x7f\0\0\0\x16\x43urve::Settings::Mode\0\0)
PlayWhileRecording=true
SimplificationRatio=100
Simplify=true

[score_plugin_engine]
Bench=false
Clock=@Variant(\0\0\0\x7f\0\0\0%Execution::ClockFactory::ConcreteKey\0\xe9\xaem\xec\xa1\xf\x41O\x90`\xb2\x1d\x15\xb5\xd5\x8d)
Commit=Merged
ExecListening=true
LogLevel=Everything
Logging=false
Merging=Merge
Ordering=Creation order
Parallel=false
Rate=50
Scheduling=Static (TC)
ScoreOrder=false
Threads=8
Tick=Buffer-accurate
TransportValueCompilation=false
ValueCompilation=true
VstAlwaysOnTop=true

[score_plugin_gfx]
Buffers=3
DecodingThreads=2
GraphicsApi=OpenGL
HardwareDecode=None
Rate=60
Samples=1
VSync=true
